#!/usr/bin/env swift
import Foundation

let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
let sourceRoot = root.appendingPathComponent("skills/banny-studio")
let output = root.appendingPathComponent("Sources/BannyCLI/GeneratedSkillResources.swift")
let files = [
    "SKILL.md",
    "agents/openai.yaml",
    "references/media-stage.md",
    "references/performance.md",
    "references/project-format.md",
    "references/speech-audio.md",
]

var lines = [
    "// Generated by tools/embed-skill.swift. Edit skills/banny-studio, not this file.",
    "import Foundation",
    "",
    "private func decodeEmbeddedSkillFile(_ base64: String) -> String {",
    "    String(decoding: Data(base64Encoded: base64)!, as: UTF8.self)",
    "}",
    "",
    "let embeddedSkillFiles: [String: String] = [",
]
for path in files {
    let data = try Data(contentsOf: sourceRoot.appendingPathComponent(path))
    lines.append("    \(String(reflecting: path)): decodeEmbeddedSkillFile(\(String(reflecting: data.base64EncodedString()))),")
}
lines.append("]")
lines.append("")
let generated = lines.joined(separator: "\n")

if CommandLine.arguments.contains("--check") {
    let current = (try? String(contentsOf: output, encoding: .utf8)) ?? ""
    if current != generated {
        FileHandle.standardError.write(Data("embedded skill is stale; run: swift tools/embed-skill.swift\n".utf8))
        exit(1)
    }
} else {
    try generated.write(to: output, atomically: true, encoding: .utf8)
    print("generated \(output.path)")
}
